### ISSUE TITLE
Frame-Check Sequence implementation

### ISSUE THREAD

**Issue by jgromes** [kicksat/ax25#3]
Hi, I'm working on AX.25 implementation for [RadioLib](https://github.com/jgromes/RadioLib), and since this is the only AX.25 implementation I was able to find, I'm using this to get a bit more of an understanding about the protocol.

I noticed you're implementing CCITT CRC as the frame check sequence, and was wondering if that really is the correct CRC to use, as the [2.2 specification ](https://www.tapr.org/pdf/AX25.2.2.pdf) calls for ISO 3309 to be used. I was unable to obtain the standard (since it's behind paywall, as usual), and quick Google search only found [one CRC implementation](https://github.com/satyendrakumarsingh/ISO-IEC-3309-compliant-16-bit-CRC-in-C-Language) that claims to be "ISO 3309 compliant" - the results of this one and yours don't match, however.

So, two questions basically:
1. Was this implementation tested against some other AX.25 implementations?
2. If so, how? In the end, I will need to test my implementation too.

I don't have any background in ham radio or packet radio, so all of this is pretty new to me. Thanks!

**Comment by zacmanchester** [comment]
It's pretty hard to find the low-level implementation details for AX.25. I got most of the info from the two pdfs in [the docs folder of the repo](https://github.com/kicksat/ax25/tree/master/docs). I tested it against the AX.25 decoder in [GQRX](http://gqrx.dk/). You can find their decoder code [here](https://github.com/csete/gqrx/tree/master/src/dsp/afsk1200). Happy to help out since I'd love to have a library like yours with AX.25 support. BTW, have you considered a [CircuitPython](https://circuitpython.readthedocs.io/en/4.x/README.html) port?

**Comment by jgromes** [comment]
Thanks for the response, I'll definitely give GQRX a shot (once I get it running on VM, as I'm working on Windows).

I haven't considered CircuitPython port - to be honest, I never used it (and it's been a few years since I did anything in Python). I'm not sure it would be easy, as RadioLib is using some C++ features that might not be available in Python, like pure virtual methods, or converting constructors.

**Comment by jgromes** [comment]
Hi again, I managed to decode AX.25 frames using SDR Console (to get the AFSK output) + SoundModem (to decode the audio) on Windows, since GQRX on VM was far too slow.

I noticed that the frames are quite long, the following seems to be cause:

https://github.com/kicksat/ax25/blob/fe6b92d22c8fdb833045f16efb14eca9689f752e/ax25.cpp#L186-L194

If my understanding of your implementation is correct, that loop will add the 0x7E flag 64 times. Was there a particular reason for this? I tried it with only one flag and SoundModem decodes it just fine.

**Comment by zacmanchester** [comment]
That's the preamble. Most decoders expect some minimum number of 0x7E bytes, but it varies by implementation. You can definitely use fewer than 64, but one is probably risky as some decoders may fail.

**Comment by jgromes** [comment]
Can't seem to find any recommended number of preamble bytes in the specification... Will leave it up to the user then ;)

Thank you very much for the help, support for AX.25 will be added to RadioLib shortly. Is it OK to use your CCITT CRC implementation (appropriately licensed, of course)?

**Comment by zacmanchester** [comment]
Yup, of course. If you're curious what's up with the preamble thing, it's there to give the receiver PLL lots of edges to synchronize on at the beginning of the packet.

**Comment by jgromes** [comment]
Added - thank you very much, you really helped me a lot. Now RadioLib can send AX.25 via most of the supported radio modules. Onwards to APRS then I guess ;)
